### ISSUE TITLE
Cards for `/member` become massive on laptop screen

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/MUNSocWebsite#2]
## About

The cards for members become really huge on a laptop screen. This is in the /members route. Please implement a limit to how big these cards can grow

## Bounty 25

**Comment by akshatnavlani** [comment]
can i work on this??

**Comment by euphoricair7** [comment]
Could You assign me this issue?

**Comment by akshatnavlani** [comment]
I am starting the work on this. Hope you don't mind

**Comment by ananyashreyaz** [comment]
can I get assigned?

**Comment by poornapragnyah** [comment]
can you assign it to me

**Comment by siaa1308** [comment]
can you assign it to me

**Comment by anuragrao04** [comment]
@akshatnavlani yepp, I don't mind at all. Sorry for the delay in assignment. Do open a PR as soon as possible. We need updates every 30 mins or you'd be deassigned

**Comment by akshatnavlani** [comment]
Thanks

**Comment by neethanm** [comment]
can i work on this #2

**Comment by anuragrao04** [comment]
@akshatnavlani Please make a PR asap. I'm pausing assignments right now because of it being dinner time. @neethanm will assign you when @akshatnavlani exceeds the time limit for an update. @akshatnavlani you don't have to solve the issue in 30 mins, you just have to make a singular commit showing any kind of progress.

**Comment by akshatnavlani** [comment]
please check I have made the PR right now

**Comment by amrit-george** [comment]
can i get assigned this issue?

**Comment by anuragrao04** [comment]
@akshatnavlani has made a PR and has been showing progress. So I can't assign it to you @amrit-george I'm sorry

**Comment by akshatnavlani** [comment]
Do i need to do something else?? Because I have not received the points yet. @anuragrao04
