### ISSUE TITLE
Disable Dark Reader On The Site

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/MUNSocWebsite#5]
## About

Dark reader is a browser extension that makes CSS changes to every website you visit. It sometimes automatically detects a dark theme but it doesn't on this website. It makes the website look bad and add border colors that we didn't add there. 

With Dark Reader **On**:

<img width="1637" alt="image" src="https://github.com/MUNSoc-PESUECC/MUNSocWebsite/assets/77329899/67ad5027-cfb7-4915-b216-7a9da849e0fb">

With Dark Reader **Off**:

<img width="1631" alt="image" src="https://github.com/MUNSoc-PESUECC/MUNSocWebsite/assets/77329899/4c18204b-d669-4f07-99dd-91d851c7606f">

## Possible Way To Fix

You can configure your web site to tell dark reader to switch itself off on our website only. Dark reader is an open source project and has excellent docs. Look up the docs to find how to do this on the website. 

## Maximum Block Time Allowed: 20 Mins

- DO NOT WORK ON THIS BEFORE BEING ASSIGNED TO IT.
- IF YOU'RE NOT, COMMENT ON THIS ISSUE OR APPROACH THE MAINTAINER TO GET ASSIGNED
- ANY WORK MADE BEFORE GETTING ASSIGNED WILL NOT BE COUNTED. 
- THIS HELPS US AVOID MULTIPLE PEOPLE WORKING ON THE SAME ISSUE AND YOUR EFFORTS BEING UNUSED.

## Bounty Points: 30

**Comment by sanyavashist** [comment]
Hey , can this issue be assigned to me !

**Comment by RitwikAg120** [comment]
can u assign it to me

**Comment by Thatboringguy** [comment]
can you assign this to me

**Comment by amrit-george** [comment]
can i be assigned this issue?

**Comment by saivihitha17** [comment]
can i get this issue?

**Comment by Rohan123R** [comment]
Can i  please be assigned to this issue , ive been working on this for quite a while and , already pulled a request 
 and i have fixed the issue as well. Issue 1 @anuragrao04

**Comment by anuragrao04** [comment]
solved by @Rohan123R

**Comment by saivihitha17** [comment]
K cool bro

**Comment by Python-is-better-than-Java** [comment]
Can I be assigned this issue?
